version: '3.5'

services:
  openmhz-to-discord:
    container_name: openmhz-to-discord
    image: jbuchbinder/openmhz-to-discord
    restart: always
    volumes:
      - .env:/.env:ro
      - /usr/lib/x86_64-linux-gnu/libasound.so.2:/usr/lib/libasound.so.2:ro
    env_file:
      - .env

